version: '2'
services:

    #####################
    # LARAVEL
    #####################
    apache:
        build: ./build/
        links:
            - db
        volumes:
            - ./html/:/var/www/html/
        ports:
            - 8000:80

    #####################
    # DATABASE
    #####################
    db:
        image: mariadb:latest
        volumes:
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=lamp_database

    #####################
    # ADMINER
    #####################
    adminer:
        image: dehy/adminer:latest
        ports:
            - 3333:80
        depends_on:
            - db
        links:
            - db

    #####################
    # MAILHOG
    #####################
    mailhog:
        image: mailhog/mailhog
        ports:
          - 8125:1025
          - 8025:8025